<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class CategoriesCountResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {



        return [
            'id'=>$this->id,
            'name'=>$this->name,
            'count'=>$this->products_count,
            'url'=>route('product_list',['type'=>$this->slug]),
            'active'=>$request->route()->parameter('type')==$this->slug
        ];
        return parent::toArray($request);
    }

    public static function withoutWrapping()
    {
        parent::withoutWrapping(); // TODO: Change the autogenerated stub
    }
}
